#yaml-language-server: $schema=https://raw.githubusercontent.com/docker/compose/master/compose/config/compose_spec.json
version: '3.8'
services:
  aoc:
    entrypoint: /bin/bash -i
    working_dir: /app
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
  ircd:
    image: ey3ball/matrix-ircd
    restart: always
    command: ["--url", "$MATRIX_URL", "-b", "0.0.0.0:5999" ]
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: aoc
    volumes:
      - ./mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aoc
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
