#yaml-language-server: $schema=https://raw.githubusercontent.com/docker/compose/master/compose/config/compose_spec.json
version: '3.8'
services:
  aoc:
    entrypoint: /bin/bash -i
    working_dir: /app
    build: .
    network_mode: host
    stdin_open: true
    tty: true
    #ports:
    #  - 32400:32400
    volumes:
      - ./:/app
  mongo:
    image: mongo
    restart: always
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: aoc
    volumes:
      - ./mongo-data:/data/db
#  mongo-express:
#    image: mongo-express
#    restart: always
#    network_mode: host
#    #ports:
#    #  - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
